#!/bin/bash

# Run silent, run deep
SILENT=0
if [ "`basename "${0}"`" == 'isMediaMounted' ]; then
	SILENT=1
fi

# Exit cleanly if the TV path exists
MEDIA="${HOME}/media"
if [ -d "${MEDIA}/TV" ]; then
	if [ $SILENT -le 0 ]; then
		echo -n "${MEDIA}"
	fi
	exit 0
fi

# Return false if we don't find anything
exit 1
